### PR TITLE
linux support using liburing

### PR DESCRIPTION
**Pull request by Garcia6l20**
- CMake support
- io operations using liburing

### CODE REVIEW

**Comment by Garcia6l20** [comment]
All tests are passing on GCC11.
`when_all() with all task types` test fails on GCC10 because extra construction are done, 2 moves an 1 copy (GCC bug ???).

**Comment by Garcia6l20** [comment]
if someone can tell me how check for header and add compile definitions with cake it could probably help me fixing CI

**Comment by andreasbuhr** [comment]
Hi, thanks a lot for sharing your code. How does your contribution compare to https://github.com/lewissbaker/cppcoro/pull/160?

**Comment by Garcia6l20** [comment]
> Hi, thanks a lot for sharing your code. How does your contribution compare to #160?

It includes what 160 does not. Timed scheduling and network.
I actually did not saw that other PR.

**Comment by andreasbuhr** [comment]
@Garcia6l20 thanks again for your work. It would be great to see liburing support integrated. Your pull request addresses many different problems at once, which makes it difficult to review. It also solves problems which have already been solved in other pull requests. In the cppcoro fork at https://github.com/andreasbuhr/cppcoro I started an effort to merge the contributions from the different existing pull requests and solve only one problem at a time. One of the first steps should be to add CMake support. In https://github.com/andreasbuhr/cppcoro/tree/add_cmake_support I created a branch which does nothing but adding CMake support, based on the different pull requests which exist here. I'd like to invite you to help make it better. Once it is in a good shape, we can add a new pull request which can then (hopefully) be easily merged by Lewis. And then care about the next issue.

**Comment by Garcia6l20** [comment]
@andreasbuhr Sounds great !
I would be pleased to help you.
I know I did it a bit fast but I wanted to see cppcoro in action :)
I'll close this PR and restart from your cmake branch step by step.

**Comment by Garcia6l20** [comment]
Slowing down !

**Comment by andreasbuhr** [comment]
Great. If you need any assistance, please drop me a note at andreas@andreasbuhr.de

**Pull request closed without merging**
